export const data = [
    ['Producto', 'Precio'],
    ['Llanta', 45],
    ['Martilllo', 7],
    ['Destornillador', 10],
    ['Quit Herramientas', 56],
    ['Audifonos', 8],
    ['telefono', 80],
    ['Mouse', 15],
    ['Tarjeta Grafica', 90],
    ['Pc', 21],
    ['Teclado', 12],
    ['Estuche', 2],
    ['Dico ssd', 34],
    ['Billetera', 5],
    ['Libreta', 8],
    ['Lapices', 3],
    ['Alcazilla', 2],
    ['Libros', 5],
    ['Crayones', 2],
    ['Razuradoras', 5],
    ['Desodorante', 2],
]